let sectionTop=$(".about").offset().top;$(window).scroll(function(){$(window).scrollTop()>sectionTop-100?$(".navbar").addClass("tst"):$(".navbar").removeClass("tst")}),$(".nav-link").click(function(){$(this).addClass("active"),$(".nav-link").not(this).removeClass("active")}),$(document).ready(function(){$(".landing").fadeOut(2e3)});let datalist=[];async function getdata(e){datalist=(await (await fetch(`https://forkify-api.herokuapp.com/api/search?q=${e}`)).json()).recipes,display()}function display(){let e="";datalist.forEach(a=>{e+=`<div class="col-lg-3 col-md-4 col-sm-6 item" recpiId="${a.recipe_id}">
        <div class="card rounded-0 cardd shadow p-2 h-75 text-center">
        <div class="layer">
        <div class="d-flex flex-column">
        <i class="fa-solid color-icon fs-3 my-3 fa-magnifying-glass-plus"  data-bs-toggle="modal" data-bs-target="#exampleModal"></i>
        <i class="fa-solid color-icon fs-3 fa-heart favorite" srcimg="${a.image_url}" id="color "></i>
        </div>
            </div>
        <img src="${a.image_url}" loading="lazy" class="h-75 cardd" />
        <p class="py-2 text-black fw-bold">${a.title}</p>
        </div>
    </div>`}),document.getElementById("myRow").innerHTML=e,getitems(),getisrc()}getdata("pizza");let dataSpec=[];async function getid(e){dataSpec=(await (await fetch(`https://forkify-api.herokuapp.com/api/get?rId=${e}`)).json()).recipe,displayimage()}function displayimage(){temp="",dataSpec.ingredients.forEach(e=>{temp+=`<li class="text-muted">${e}</li>`}),document.getElementById("myimage").setAttribute("src",dataSpec.image_url),document.getElementById("list").innerHTML=temp}function getitems(){let e=document.querySelectorAll(".item");for(let a=0;a<e.length;a++)e[a].addEventListener("click",function(){getid(this.getAttribute("recpiId"))})}var listimage,color=document.getElementById("color");function getisrc(){let e=document.querySelectorAll(".favorite");for(let a=0;a<e.length;a++)e[a].addEventListener("click",function(){let e=this.getAttribute("srcimg");listimage.includes(e)?alert("Image is already in your favorite list."):(listimage.push(e),localStorage.setItem("listimage",JSON.stringify(listimage)),displayfav())})}function displayfav(){for(var e="",a=0;a<listimage.length;a++)e+=`  <div class="col-lg-3 col-md-4 col-sm-6">
    <div class="card cardd h-75  mt-5 p-3">
        <img src=" `+listimage[a]+` "class="cardd h-75" alt="">
        <button class="btn btn-outline-danger rounded-pill  mt-3" onclick="del(`+a+`)">Delete</button>
    </div>
</div>`;document.getElementById("Fav").innerHTML=e}function del(e){listimage.splice(e,1),localStorage.setItem("listimage",JSON.stringify(listimage)),displayfav()}null!=localStorage.getItem("listimage")?(listimage=JSON.parse(localStorage.getItem("listimage")),displayfav()):listimage=[];let navlinks=document.querySelectorAll(".nav-link");for(i=0;i<navlinks.length;i++)navlinks[i].addEventListener("click",function(e){getdata(this.getAttribute("categ"))});new WOW().init(),new PureCounter;var nameinput=document.getElementById("name"),emailinput=document.getElementById("email"),messageinput=document.getElementById("message"),alertmax=document.getElementById("alertmax"),mesg=document.getElementById("mesg");function addvaild(){!0==validName()&&!0==validEmail()&&!0==validPass()?(mesg.classList.replace("d-none","d-block"),$("#mesg").fadeOut(6e3),$("#mesg").removeClass("d-block"),clearinput()):(nameinput.classList.remove("is-valid"),emailinput.classList.add("is-invalid"),messageinput.classList.add("is-invalid"))}function validName(){return!0==/^[a-zA-Z0-9\s]{3,20}$/.test(nameinput.value)?(nameinput.classList.add("is-valid"),nameinput.classList.remove("is-invalid"),!0):(nameinput.classList.add("is-invalid"),nameinput.classList.remove("is-valid"),!1)}function validEmail(){return!0==/^[\w\-\.]+@([\w-]+\.)+[\w-]{2,}$/.test(emailinput.value)?(emailinput.classList.add("is-valid"),emailinput.classList.remove("is-invalid"),!0):(emailinput.classList.remove("is-valid"),emailinput.classList.add("is-invalid"),!1)}function validPass(){let e=/^[a-zA-Z0-9\s]{3,20}$/;return!0==e.test(messageinput.value)&&20>=e.test(messageinput.value)?(messageinput.classList.add("is-valid"),messageinput.classList.remove("is-invalid"),alertmax.classList.replace("d-block","d-none"),!0):(messageinput.classList.remove("is-valid"),messageinput.classList.add("is-invalid"),alertmax.classList.replace("d-none","d-block"),!1)}function clearinput(){nameinput.value="",emailinput.value="",messageinput.value="",nameinput.classList.remove("is-valid"),emailinput.classList.remove("is-valid"),messageinput.classList.remove("is-valid")}nameinput.addEventListener("blur",validName),emailinput.addEventListener("blur",validEmail),messageinput.addEventListener("blur",validPass);